export const CREATE_DATASET_START = 'CREATE_DATASET_START';
export const CREATE_DATASET_COMPLETE = 'CREATE_DATASET_COMPLETE';
export const CREATE_DATASET_SUCCESS = 'CREATE_DATASET_SUCCESS';
export const CREATE_DATASET_ERROR = 'CREATE_DATASET_ERROR';

export const IMPORT_DATASET_START = 'IMPORT_DATASET_START';
export const IMPORT_DATASET_COMPLETE = 'IMPORT_DATASET_COMPLETE';
export const IMPORT_DATASET_SUCCESS = 'IMPORT_DATASET_SUCCESS';
export const IMPORT_DATASET_ERROR = 'IMPORT_DATASET_ERROR';

export const LOAD_DATASETS_START = 'LOAD_DATASETS_START';
export const LOAD_DATASETS_COMPLETE = 'LOAD_DATASETS_COMPLETE';
export const LOAD_DATASETS_SUCCESS = 'LOAD_DATASETS_SUCCESS';
export const LOAD_DATASETS_ERROR = 'LOAD_DATASETS_ERROR';

export const DELETE_DATASET_START = 'DELETE_DATASET_START';
export const DELETE_DATASET_COMPLETE = 'DELETE_DATASET_COMPLETE';
export const DELETE_DATASET_SUCCESS = 'DELETE_DATASET_SUCCESS';
export const DELETE_DATASET_ERROR = 'DELETE_DATASET_ERROR';

export const LOAD_DATASET_STATS_START = 'LOAD_DATASET_STATS_START';
export const LOAD_DATASET_STATS_COMPLETE = 'LOAD_DATASET_STATS_COMPLETE';
export const LOAD_DATASET_STATS_SUCCESS = 'LOAD_DATASET_STATS_SUCCESS';
export const LOAD_DATASET_STATS_ERROR = 'LOAD_DATASET_STATS_ERROR';

export const LOAD_DATASET_CONNECTIONS_START = 'LOAD_DATASET_CONNECTIONS_START';
export const LOAD_DATASET_CONNECTIONS_COMPLETE = 'LOAD_DATASET_CONNECTIONS_COMPLETE';
export const LOAD_DATASET_CONNECTIONS_SUCCESS = 'LOAD_DATASET_CONNECTIONS_SUCCESS';
export const LOAD_DATASET_CONNECTIONS_ERROR = 'LOAD_DATASET_CONNECTIONS_ERROR';